// <auto-generated />
using System;
using APIProjeto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIProjeto.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251116041429_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("APIProjeto.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdDemanda")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioRegulador")
                        .HasColumnType("int");

                    b.Property<int>("IdVaga")
                        .HasColumnType("int");

                    b.Property<string>("StatusComparecimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Agendamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataAgendamento = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataRealizacao = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdDemanda = 1,
                            IdUsuarioRegulador = 2,
                            IdVaga = 1,
                            StatusComparecimento = "Pendente"
                        });
                });

            modelBuilder.Entity("APIProjeto.Models.Demanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdProcedimento")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidadeSolicitante")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioSolicitante")
                        .HasColumnType("int");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Demandas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataSolicitacao = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPaciente = 1,
                            IdProcedimento = 1,
                            IdUnidadeSolicitante = 1,
                            IdUsuarioSolicitante = 3,
                            Justificativa = "Paciente com dor no peito",
                            Prioridade = "Alta",
                            Status = "Aguardando"
                        });
                });

            modelBuilder.Entity("APIProjeto.Models.Especialidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Cardiologia"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Ortopedia"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Pediatria"
                        });
                });

            modelBuilder.Entity("APIProjeto.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cns")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cns = "998877665544",
                            Cpf = "12345678900",
                            DataNascimento = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rua A, 123",
                            Nome = "João da Silva"
                        },
                        new
                        {
                            Id = 2,
                            Cns = "112233445566",
                            Cpf = "98765432100",
                            DataNascimento = new DateTime(1985, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rua B, 45",
                            Nome = "Maria Oliveira"
                        });
                });

            modelBuilder.Entity("APIProjeto.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Perfil");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Regulador"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Solicitante"
                        });
                });

            modelBuilder.Entity("APIProjeto.Models.Procedimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoProcedimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdEspecialidade")
                        .HasColumnType("int");

                    b.Property<string>("NomeProcedimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Procedimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoProcedimento = "PROC001",
                            IdEspecialidade = 1,
                            NomeProcedimento = "Consulta Cardiologia",
                            Tipo = "Consulta"
                        },
                        new
                        {
                            Id = 2,
                            CodigoProcedimento = "PROC002",
                            IdEspecialidade = 2,
                            NomeProcedimento = "Raio-X de Mão",
                            Tipo = "Exame"
                        });
                });

            modelBuilder.Entity("APIProjeto.Models.UnidadeSaude", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UnidadesSaude");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "UBS Central",
                            Regiao = "Centro",
                            Tipo = "UBS"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "UPA Norte",
                            Regiao = "Zona Norte",
                            Tipo = "UPA"
                        });
                });

            modelBuilder.Entity("APIProjeto.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidadeSaude")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "00000000000",
                            IdPerfil = 1,
                            IdUnidadeSaude = 1,
                            Nome = "Administrador",
                            Senha = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Cpf = "11111111111",
                            IdPerfil = 2,
                            IdUnidadeSaude = 1,
                            Nome = "Regulador Teste",
                            Senha = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Cpf = "22222222222",
                            IdPerfil = 3,
                            IdUnidadeSaude = 2,
                            Nome = "Solicitante Teste",
                            Senha = "123456"
                        });
                });

            modelBuilder.Entity("APIProjeto.Models.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdProcedimento")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidadeOfertante")
                        .HasColumnType("int");

                    b.Property<string>("MesAnoReferencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vagas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdProcedimento = 1,
                            IdUnidadeOfertante = 1,
                            MesAnoReferencia = "01/2025",
                            Quantidade = 10
                        },
                        new
                        {
                            Id = 2,
                            IdProcedimento = 2,
                            IdUnidadeOfertante = 2,
                            MesAnoReferencia = "01/2025",
                            Quantidade = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
